name: Github Actions - assignment 3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      # Typecheck
      - name: TSC actions
        run: npm install
            npx tsc --noEmit
      #Prettier check
      - name: Prettier Check
        uses: rutajdash/prettier-cli-action@v1.0.0
      # Testing with coverage
      - name: Test with report
        run: npm run test-report
        
      #job status
      - run: echo "This job's status is ${{ job.status }}."
